[ukhasnet]
socket = "ukhas.net:3010"

[influxdb]
url = "http://localhost:8086/write?db=ukhasnet"
username = "ukhasnet"
password = "{{ pillar['ukhasnet']['influxdb']['users']['ukhasnet']['password'] }}"
